version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: social_media_platform
      POSTGRES_USER: social_user_dev
      POSTGRES_PASSWORD: dev_password_123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U social_user_dev -d social_media_platform"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: social_media_platform_data
